### ISSUE TITLE
Direct link

### ISSUE THREAD

**Issue by abhishekkrthakur** [Glorf/recipenlg#2]
Is there a direct link to the dataset?

**Comment by sam0x17** [comment]
I also have an interest in the dataset itself

**Comment by thomasvidas** [comment]
It is already laid out in the README under the `Where is the dataset?` section.

https://recipenlg.cs.put.poznan.pl/

**Comment by abhishekkrthakur** [comment]
Thank you. Maybe I didnt clarify myself enough. By direct link, I meant a link that I can use to download the dataset directly using wget or curl. The current link includes a form and captcha. :)

**Comment by Glorf** [comment]
Hello, thanks for your interest
Yes, the dataset is available on the website. We don't provide direct link for purpose - as the uncertainty about the legal aspects of our dataset force us to provide it on rather strict conditions, which you have to accept to gain access. 

Sorry for that, I hope that the legislation behind scraping will get clearer one day.

**Comment by abhishekkrthakur** [comment]
Thanks @Glorf

**Comment by sam0x17** [comment]
One thing that might be of interest -- at least in the U.S. there is now legal precedent set in the recent (2018) LinkedIn case that bots are not subject to terms of service, full stop. While copyright law is still something you have to worry about, the actual act of scraping is no longer a gray area. Scrape whatever you want.

**Comment by lbordowitz** [comment]
I'm not currently able to access the dataset, captcha or otherwise. Is the current recommendation to scrape the sites with the scripts you've provided?

**Comment by Glorf** [comment]
> I'm not currently able to access the dataset, captcha or otherwise. Is the current recommendation to scrape the sites with the scripts you've provided?

Thank you for information, the website was down for a moment, now everything should be back in order
