### ISSUE TITLE
Recipe error

### ISSUE THREAD

**Issue by obriensoftwarehouse** [Glorf/recipenlg#3]
Recipe Title: 4 Ingredient Sauce for Roasted Lamb
Source: https://www.food.com/recipe/4-ingredient-sauce-for-roasted-lamb-211702
![recipe error](https://user-images.githubusercontent.com/8349116/101737022-0091c200-3b10-11eb-8544-6487990a8716.png)

Says to use 12 cups of brown sugar. The source site has 1/2 (0.5) cups.

Really not sure if this is the right place to put this, but I'll let you guys decide.

**Comment by Glorf** [comment]
Thanks! Yes, it's caused by the part of recipes from Recipe1M (the older dataset), you have to filter the dataset for source "Gathered" to access only the well-prepared recipes (~1.8M). The details of the process and differences between two sets are detailed in our papers
